# Automatically created from terraform data on 

all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
    ansible_become: true
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/bootcamp.pem

    regenerate_keystore_and_truststore: true
    deployment_strategy: parallel

    jmxexporter_enabled: true


zookeeper:
  hosts:
    ip-172-32-1-148.eu-west-1.compute.internal:
    ip-172-32-2-84.eu-west-1.compute.internal:
    ip-172-32-3-130.eu-west-1.compute.internal:
    
kafka_broker:
  hosts:
    ip-172-32-1-12.eu-west-1.compute.internal:
    ip-172-32-2-227.eu-west-1.compute.internal:
    ip-172-32-3-178.eu-west-1.compute.internal:
    

schema_registry:
  hosts:
    ip-172-32-1-99.eu-west-1.compute.internal:
    

kafka_rest:
  hosts:
    

ksql:
  hosts:
    ip-172-32-1-129.eu-west-1.compute.internal:
    

kafka_connect:
  hosts:
    ip-172-32-1-161.eu-west-1.compute.internal:
    ip-172-32-2-61.eu-west-1.compute.internal:
    

control_center:
  hosts:
    ip-172-32-1-66.eu-west-1.compute.internal:
    
